version: '5.7'

services:
  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=mysecretpassword'
    ports:
      - '5444:5432'
